name: financial-connections-example maestro
on:
  pull_request:
    paths:
      - 'financial-connections/**'
      - 'financial-connections-example/**'
      - 'stripe-core/**'
      - 'payments-model/**'
      - 'dependencies.gradle'
jobs:
  build:
    runs-on: macos-latest
    env:
      AVD_API_LEVEL: 30
      AVD_ARCH: x86_64
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ env.AVD_API_LEVEL }}-${{ env.AVD_ARCH }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.AVD_API_LEVEL }}
          arch: ${{ env.AVD_ARCH }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Install Maestro CLI
        run: curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: Add Maestro to path
        run: echo "${HOME}/.maestro/bin" >> $GITHUB_PATH

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.AVD_API_LEVEL }}
          arch: ${{ env.AVD_ARCH }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            adb root || true
            adb uninstall com.stripe.android.financialconnections.example || true
            mkdir -p financial-connections-example/build/reports
            ./gradlew :financial-connections-example:installDebug
            adb shell screenrecord --verbose /storage/emulated/0/capture.mp4 &
            childpid=$!
            maestro test maestro/fc-flow-test-oauth.yaml || true
            kill "$childpid"
            wait "$childpid"
            cd financial-connections-example/build/reports/ && adb pull /storage/emulated/0/capture.mp4

      - name: Archive screen record
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: screenrecord
          path: financial-connections-example/build/reports/

      - name: Archive maestro screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: maestro-screenshots
          path: |
            *.png
